### ISSUE TITLE
Using the 'config' field

### ISSUE THREAD

**Issue by noahbald** [whitespace-se/storybook-addon-html#103]
When running the addon in Storybook 7.0.26, I get the following warning.

`You (or an addon) are using the 'config' preset field. This has been replaced by 'previewAnnotations' and will be removed in 8.0`

If I remove this addon, the warning goes away.

**Comment by cotwitch** [comment]
I'm also noticing this.

Occuring on Storybook 7.4.0 `storybook-vite` using `@storybook/html` and `@storybook/html-vite`

When fixed, this page could be "pinged" [here](https://github.com/storybookjs/storybook/issues/20529)

**Comment by arcticShadow** [comment]
Removing this line https://github.com/whitespace-se/storybook-addon-html/blob/main/preset.js#L15 seems to make the error go away in v7 of storybook. 

From what I can tell, The change required for v7 appears to be that the `config` export is updated to `previewAnnotations` - however, since `previewAnnotations` is already there, it seems this addon is already correctly configured for v7. 

Which leaves me thinking that it may be intentional to have both `config` and `previewAnnotations` exported. Although I don't know why - I have a theory with no basis or research, that it would be to support Storybook 6 & 7 at the same time.
