### ISSUE TITLE
storybook 6.1.10 + ie11 isn't working = highlightjs isnt babel'd

### ISSUE THREAD

**Issue by dutscher** [whitespace-se/storybook-addon-html#38]
using the newest: `"@whitespace/storybook-addon-html": "^4.2.0",`
and default storybook babel and webpack config.

And here the main.js addon config:
![image](https://user-images.githubusercontent.com/14682/104311336-5540a800-54d5-11eb-8acd-ae5a1eceee2b.png)

This combi will break the IE11:
![image](https://user-images.githubusercontent.com/14682/104311749-f4659f80-54d5-11eb-89b7-9b62c78b84b2.png)
![image](https://user-images.githubusercontent.com/14682/104311870-20812080-54d6-11eb-9260-fdd0d9a3bd53.png)
`class Response` isn't ready for es5

here a chrome console output:
![image](https://user-images.githubusercontent.com/14682/104312169-88376b80-54d6-11eb-933d-84d795c71b97.png)

and then i found that `highlight.js`. this file isn't babel'd yet `node_modules/highlight.js/lib/core.js` which is required by `"react-syntax-highlighter": "^15.4.3"`.
but your https://github.com/whitespace-se/storybook-addon-html/blob/master/addon/.babelrc has exactly the `plugin-proposal-class-properties`. 

what can i do to fix this issue? 
thanks in advance.

cheers

**Comment by dutscher** [comment]
its releated to https://github.com/highlightjs/highlight.js/issues/2501 they dropped ie11 support in v10.
maybe there is no hope to get this working :)

cheers

**Comment by jeanfredrik** [comment]
One option would be to downgrade react-syntax-highlighter from 15 to 13. That shouldn’t be problem though because this addon doesn’t rely on any of the features listed as breaking changes in neither [Highlight.js](https://github.com/highlightjs/highlight.js/blob/main/VERSION_10_BREAKING_CHANGES.md) or [react-syntax-highlighter]((https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/master/CHANGELOG.MD).

Right now I can’t get the latest version of Storybook (6.2.9) to work in IE11 at all though because of [this issue](https://github.com/storybookjs/storybook/issues/14578). When it's solved, we can give this a try.

**Comment by jeanfredrik** [comment]
From version 5 of this addon react-syntax-highlighter is a peer dependency that you install manually, so downgrading would be easy. I'm not sure if IE11 is still a requirement for you though. I will close this issue for now.
